kind: template
load: chronos-vue-ac-pop.yml
data:
  deploy_file: deploy/husthole.yaml
  docker_repo: registry.cn-hangzhou.aliyuncs.com/mo2/mo2-front
  docker_registry: registry.cn-hangzhou.aliyuncs.com
  default_branch: master
  docker_user_name_secret: docker_user_name # docker_user_name is not a placeholder, do not change this if you are using pivot studio's repo
  docker_pass_secret: docker_pass # docker_pass is not a placeholder, do not change this if you are using pivot studio's repo