kind: pipeline
type: kubernetes
name: default
trigger:
  event:
    - pull_request
    - push
steps:
  - name: build 
    image: node:14
    commands:
      - npm config set registry https://registry.npm.taobao.org
      - rm package-lock.json
      - npm cache clean --force
      - npm cache verify
      - npm install
      - npm run build
    when:
      ref:
        include:
        - refs/pull/**
  - name: ci build 
    image: node:14
    environment:
      qiniuak:
        from_secret: qiniuak
      qiniusk:
        from_secret: qiniusk
      GIN_MODE: release
    commands:
      - npm config set registry https://registry.npm.taobao.org
      - npm cache verify
      - npm install
      - npm run build
      - cp -r dist /home/dist
      - ls /home/dist
      - ./qiniu_uploader
    when:
      ref:
        include:
        - refs/heads/master
  - name: docker  
    image: plugins/docker
    depends_on:
      - "ci build"
    settings:
      username: 
        from_secret: docker_user_name
      password: 
        from_secret: docker_pass
      repo: registry.cn-hangzhou.aliyuncs.com/mo2/mo2-front
      registry: registry.cn-hangzhou.aliyuncs.com
      mirror: https://jtkrmusq.mirror.aliyuncs.com
      tags:
        - latest
        - build-${DRONE_BUILD_NUMBER} 
    when:
      branch:
       - master
      event:
      - push
  - name: k8s cd
    image: bh90210/dron8s:latest
    depends_on:
      - "docker"
    settings:
      yaml: deploy/mo2front.yaml
      build_tag: build-${DRONE_BUILD_NUMBER}
    when:
      branch:
      - master
      event:
      - push